//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM.Key.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDM.Key.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate.
        /// </summary>
        internal static string activate {
            get {
                return ResourceManager.GetString("activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] cmd {
            get {
                object obj = ResourceManager.GetObject("cmd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @setlocal DisableDelayedExpansion
        ///@echo off
        ///
        ///
        ///::  To activate, run the script with &quot;/act&quot; parameter or change 0 to 1 in below line
        ///set _activate=0
        ///
        ///::  To Freeze the 30 days trial period, run the script with &quot;/frz&quot; parameter or change 0 to 1 in below line
        ///set _freeze=0
        ///
        ///::  To reset the activation and trial, run the script with &quot;/res&quot; parameter or change 0 to 1 in below line
        ///set _reset=0
        ///
        ///::  If value is changed in above lines or parameter is used then script will run in unattended mode
        ///
        ///::== [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string com {
            get {
                return ResourceManager.GetString("com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The first name/surname cannot be emptied.
        /// </summary>
        internal static string errorEmptyFields {
            get {
                return ResourceManager.GetString("errorEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name:.
        /// </summary>
        internal static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Freeze trial.
        /// </summary>
        internal static string freeze {
            get {
                return ResourceManager.GetString("freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name:.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options menu.
        /// </summary>
        internal static string optionMenu {
            get {
                return ResourceManager.GetString("optionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Readme.
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset trial / activation.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customize activation.
        /// </summary>
        internal static string titleCustom {
            get {
                return ResourceManager.GetString("titleCustom", resourceCulture);
            }
        }
    }
}
